### ISSUE TITLE
fbstatus does not render correctly on all monitor resolutions

### ISSUE THREAD

**Issue by WhiteHexagon** [gokrazy/fbstatus#3]
## Platform

I’m using:
* [x] gokrazy/rpi4b

## Observed behavior
A couple hiccups with the Quickstart guide, but finally managed to boot the new image.  I see maybe a page and a half of small text fly up the left side of the screen, and then my dell monitor says there is a timing issue, and requests a change to 1920x1200@60Hz.  Same thing on Pi400.  Not sure where to check/change the resolution, and cant see anything obvious in the various repos or docu.  Also not sure how this is gonna connect to my wifi network, since it seems to expect ethernet?

## Expected behavior
some kind of successful boot (just the 'hello' app installed)

**Comment by WhiteHexagon** [comment]
Let me know if there is anything I can do to help/test.  e.g. I was trying to see if the boot sequence for the Pi4 was logged somewhere, but I am guessing I would need to setup the writable partition first?  I had a look at the fb code, but couldn't see anything obviously different with the logo rendering, apart from maybe it takes longer than a frame to render, but dont see why that would impact it.

**Comment by stapelberg** [comment]
> I was trying to see if the boot sequence for the Pi4 was logged somewhere, but I am guessing I would need to setup the writable partition first?

With `-serial_console=disabled`, all boot output ends up on the HDMI console (if you include `fbstatus`, that will obviously clear the screen).

As the HDMI console can scroll past pretty quickly, my preferred solution to see (and potentially capture) the full logs is to use a USB-to-serial adapter connected to the Raspberry Pi’s RX/TX pins (remove the `-serial_console=disabled` flag of course).

The permanent partition won’t help, as nothing is logged to it by default. 

You can optionally [enable remote syslog](https://gokrazy.org/userguide/remotesyslog/), but that only covers application logs, not kernel logs. 

> I had a look at the fb code, but couldn't see anything obviously different with the logo rendering

I’m pretty certain the relevant difference is the screen resolution. Maybe best for development would be to render to some other place (a PNG file?) and try a couple of typical screen resolutions.

**Comment by WhiteHexagon** [comment]
ok I managed to get an old Arduino FTDI and the arduino 'serial monitor' running and connected to the Pi4, phew!  The video config looks good:

```[    0.000000] Kernel command line: video=HDMI-A-1:1920x1200M@60 dma.dmachans=0x37f5 bcm2709.boardrev=0xc03111 bcm2709.serial=0xd3b8fa7c bcm2709.uart_clock=48000000 bcm2709.disk_led_gpio=42 bcm2709.disk_led_active_low=0 smsc95xx.macaddr=xxxx vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=tty1 console=ttyS0,115200 root=PARTUUID=xxxx/PARTNROFF=1 init=/gokrazy/init rootwait panic=10 oops=panic```

which is the same as my monitor is requesting when the display fails.  1920x1200@60

The good news is I can see the device continues to post, and I can actually access the 'hello' service via the web interface, yay!

PS When I create the image using the Pi4, I keep forgetting to ```umount /dev/sda2```  The process stops saying it is mounted, but it is not clear this is a failure message requiring the umount.  Not sure if that is just a quirk of the way I am creating the sdcard image, or something that might trip up others.
